version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
    environment:    
      - POSTGRES_USER 
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  redis:
    image: redis:6
    container_name: redis
    ports:
      - 6379:6379
